### ISSUE TITLE
Formulación

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/SoundWave#11]

**Comment by jahirfiquitiva** [comment]
@cristhiancarrero 
Por favor...
- Revisar el [aporte](https://docs.google.com/document/d/1aZShDtrYQzapD--L54U5FgarbCMuIJRFMxlhgp7FM9k/edit?disco=AAAAB0Z1aY4) de @jsmnss
- Modificar la pregunta para que sea respecto a lo que se espera del proyecto, no a los usuarios... Básicamente, el desarrollo del proyecto, debe dar respuesta a esa pregunta.
- Complementar la pregunta para que quede de unos 5 renglones.

**Comment by jsmnss** [comment]
Segun la guia que nos dio el profesor para el punto 2 que es donde va todo lo relacionado con software, no hay ninguna cosa donde se pueda meter la formulación
