### ISSUE TITLE
Diagramas de Gestión de Comunicaciones

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/SoundWave#33]

**Comment by jsmnss** [comment]
No sé que mas agregarle a la tabla de la dimensión de comunicaciones

**Comment by jahirfiquitiva** [comment]
Ok... Mañana le decimos al ingeniero que lo revise ... Por favor, páselo al documento principal @jsmnss

**Comment by jsmnss** [comment]
Completar la descripción de la tabla

**Comment by jsmnss** [comment]
- [x] Descripción de la tabla de la gestión de las comunicaciones
